//generated by the help of the mighty AI

document.addEventListener('DOMContentLoaded', function () {
    // Function to create and show the popup
    function showPopup() {
        // Create the popup overlay
        const popupOverlay = document.createElement('div');
        popupOverlay.id = 'popup-overlay';

        // Create the popup
        const popup = document.createElement('div');
        popup.id = 'popup';

        // Create the popup header
        const header = document.createElement('h2');
        header.textContent = '选择包间';
        popup.appendChild(header);

        // Create the button container
        const buttonContainer = document.createElement('div');
        buttonContainer.className = 'button-container';
        popup.appendChild(buttonContainer);

        // Append the popup to the overlay
        popupOverlay.appendChild(popup);
        document.body.appendChild(popupOverlay);

        // Close popup when clicking outside
        popupOverlay.addEventListener('click', function(event) {
            if (event.target === popupOverlay) {
                document.body.removeChild(popupOverlay);
            }
        });

        // Define unavailable seats
        const unavailableSeats = [7, 9, 14];

        // Generate buttons
        for (let i = 1; i <= 16; i++) {
            const button = document.createElement('button');
            button.textContent = i + '号包间';
            if (unavailableSeats.includes(i)) {
                button.disabled = true;
            } else {
                button.addEventListener('click', function() {
                    alert(`You selected room ${i}号包间`);
                    document.body.removeChild(popupOverlay);
                });
            }
            if (i === 1) {
                button.classList.add('highlighted'); // Highlight the 1号包间 button
            }
            buttonContainer.appendChild(button);
        }
    }

    // Open popup when the page loads
    showPopup();

    // Open popup when the div is clicked
    const openPopupDiv = document.getElementById('open-popup');
    openPopupDiv.addEventListener('click', showPopup);
});
