//generated by the help of the mighty AI

function toggleDropdown(element) {
    // Close any currently open drops
    const alldrops = document.querySelectorAll('.drop-container');
    alldrops.forEach(drop => {
        if (drop !== element && drop.classList.contains('open')) {
            drop.classList.remove('open');
            const dropContents = drop.querySelectorAll('.drop-content');
            dropContents.forEach(content => {
                content.style.display = 'none';
            });
        }
    });

    // Toggle the clicked drop
    element.classList.toggle('open');
    const dropContents = element.querySelectorAll('.drop-content');
    dropContents.forEach(content => {
        if (element.classList.contains('open')) {
            content.style.display = 'block';
        } else {
            content.style.display = 'none';
        }
    });

    // Add click event listener to navigate to place-order-ktv.html and stop propagation
    dropContents.forEach(content => {
        content.addEventListener('click', (event) => {
            event.stopPropagation(); // Prevents the event from bubbling up to the parent
            window.location.href = 'ktv-food.html';
        });
    });
}

