//All these Javascript function fully generated by the help of AI

document.addEventListener('DOMContentLoaded', (event) => {
    const upsellContainer = document.getElementById('upsell');

    upsellContainer.addEventListener('wheel', (e) => {
        if (e.deltaY !== 0) {
            e.preventDefault();
            smoothScroll(upsellContainer, e.deltaY);
        }
    });

    function smoothScroll(element, deltaY) {
        const scrollAmount = deltaY;
        const scrollStep = 5;
        const scrollInterval = 10; // milliseconds

        let scrollRemaining = Math.abs(scrollAmount);
        let scrollDirection = deltaY > 0 ? 1 : -1;

        function step() {
            if (scrollRemaining > 0) {
                element.scrollBy(scrollStep * scrollDirection, 0);
                scrollRemaining -= scrollStep;
                requestAnimationFrame(step);
            }
        }

        step();
    }
});